### ISSUE TITLE
Error when having more than one instance

### ISSUE THREAD

**Issue by antopilo** [StudioCherno/Coral#7]
It seems when you create more than one instance of a type.

For example, if you have an `EntityScript` type and you create two classes that inherit from `EntityScript` with this simple setup:

```csharp
public class EntityScript {
    internal unsafe static delegate*<uint, bool> EntityHasComponentIcall;
    
    public virtual void OnInit() { }
    public virtual void OnUpdate(float dt) { }
    public virtual void OnFixedUpdate(float dt) { }
    public virtual void OnDestroy() { }
}
```

And then have two scripts inheriting from this class:
```csharp
public class FPSCamera : EntityScript {
    public override void OnInit() {}
}

public class Player : EntityScript {
    public override void OnInit() {}
}
```

Calling `OnInit()` from C++ works fine when you have 1 entity but as soon as you have more than one, the method invokations don't resolve.

The instances are creating by calling `CreateInstance()` on both types (FPSCamera, Player) and doing `InvokeMethod` on those instances.

This is a blocking issue preventing from creating multiple entity scripts and calling the necessary methods without managing all the callbacks manually in the C# side and tracking entities there, which is less than ideal for performance reasons and adds an extra layer of indirection.

**Comment by peter1745** [comment]
Will be looking into this today, guessing it's a problem with my method caching system

**Comment by peter1745** [comment]
The issue is caused by `MethodKey` not accounting for the type when generating the hash
